version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "wallstop"
    reviewers:
      - "wallstop"
    commit-message:
      prefix: "chore(ci)"
    groups:
      ci-runtime-actions:
        patterns:
          - "actions/checkout"
          - "actions/setup-node"
      other-github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/checkout"
          - "actions/setup-node"
    open-pull-requests-limit: 5
