#!/usr/bin/env bash
set -euo pipefail

reject_untrusted_request() {
  test "${REQUEST_CONCLUSION:?REQUEST_CONCLUSION is required}" = "success"
  test "${REQUEST_HEAD_BRANCH:?REQUEST_HEAD_BRANCH is required}" = "main"
  test "${REQUEST_HEAD_REPOSITORY:?REQUEST_HEAD_REPOSITORY is required}" = "${TRUSTED_REPOSITORY:?TRUSTED_REPOSITORY is required}"
}

validate_request() {
  jq -e '
    type == "object" and
    (keys | sort) == ["allowWorkflowDispatch", "defaultBranch", "fork", "repository"] and
    (.repository | type == "string") and
    (.defaultBranch | type == "string") and
    (.fork | type == "boolean") and
    (.allowWorkflowDispatch | type == "boolean")
  ' "${REQUEST_PATH:?REQUEST_PATH is required}" >/dev/null
  repository="$(jq -er .repository "${REQUEST_PATH}")"
  default_branch="$(jq -er .defaultBranch "${REQUEST_PATH}")"
  fork="$(jq -r .fork "${REQUEST_PATH}")"
  allow_dispatch="$(jq -r .allowWorkflowDispatch "${REQUEST_PATH}")"
  go run ./cmd/onboard-unity-repository \
    --policy unity-enrollment-policy.json \
    --repository "${repository}" \
    --default-branch "${default_branch}" \
    --fork="${fork}" \
    --allow-workflow-dispatch="${allow_dispatch}" \
    --validate-only
  {
    echo "repository=${repository}"
    echo "repository_name=${repository#*/}"
    echo "default_branch=${default_branch}"
    echo "fork=${fork}"
    echo "allow_dispatch=${allow_dispatch}"
  } >> "${GITHUB_OUTPUT:?GITHUB_OUTPUT is required}"
}

verify_target() {
  metadata="$(GH_TOKEN="${READER_AUTHORIZATION:?READER_AUTHORIZATION is required}" gh api "repos/${TARGET_REPOSITORY:?TARGET_REPOSITORY is required}")"
  test "$(jq -r .full_name <<<"${metadata}")" = "${TARGET_REPOSITORY}"
  test "$(jq -r .default_branch <<<"${metadata}")" = "${TARGET_DEFAULT_BRANCH:?TARGET_DEFAULT_BRANCH is required}"
  test "$(jq -r .fork <<<"${metadata}")" = "${TARGET_FORK:?TARGET_FORK is required}"
  target_sha="$(
    GH_TOKEN="${READER_AUTHORIZATION}" \
      gh api "repos/${TARGET_REPOSITORY}/git/ref/heads/${TARGET_DEFAULT_BRANCH}" \
      --jq .object.sha
  )"
  if [[ ! "${target_sha}" =~ ^[a-f0-9]{40}$ ]]; then
    echo "The target branch head is not an immutable commit SHA." >&2
    exit 1
  fi
  echo "sha=${target_sha}" >> "${GITHUB_OUTPUT:?GITHUB_OUTPUT is required}"
}

update_policy() {
  go run ./cmd/onboard-unity-repository \
    --policy unity-enrollment-policy.json \
    --repository "${TARGET_REPOSITORY:?TARGET_REPOSITORY is required}" \
    --default-branch "${TARGET_DEFAULT_BRANCH:?TARGET_DEFAULT_BRANCH is required}" \
    --fork="${TARGET_FORK:?TARGET_FORK is required}" \
    --allow-workflow-dispatch="${TARGET_ALLOW_WORKFLOW_DISPATCH:?TARGET_ALLOW_WORKFLOW_DISPATCH is required}"
  go test ./internal/enrollment ./cmd/onboard-unity-repository
}

open_pr() {
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git checkout -b "${ONBOARDING_BRANCH:?ONBOARDING_BRANCH is required}"
  git add unity-enrollment-policy.json
  git commit -m "chore: enroll ${TARGET_REPOSITORY:?TARGET_REPOSITORY is required} in Unity audit"
  git push origin "${ONBOARDING_BRANCH}"
  body="$(
    printf '%s\n' \
      'Generated by trusted-main Unity repository onboarding.' \
      '' \
      'Authoritative pre-merge evidence:' \
      "- Repository: \`${TARGET_REPOSITORY}\`" \
      "- Default branch: \`${TARGET_DEFAULT_BRANCH:?TARGET_DEFAULT_BRANCH is required}\`" \
      "- Fork: \`${TARGET_FORK:?TARGET_FORK is required}\`" \
      "- Verified target head: \`${TARGET_SHA:?TARGET_SHA is required}\`" \
      "- Reader App installation and Contents-read access: verified" \
      "- Evidence run: ${EVIDENCE_RUN_URL:?EVIDENCE_RUN_URL is required}"
  )"
  gh pr create \
    --base main \
    --head "${ONBOARDING_BRANCH}" \
    --title "chore: enroll ${TARGET_REPOSITORY} in Unity audit" \
    --body "${body}"
}

case "${1:-}" in
  reject-untrusted-request) reject_untrusted_request ;;
  validate-request) validate_request ;;
  verify-target) verify_target ;;
  update-policy) update_policy ;;
  open-pr) open_pr ;;
  *)
    echo "usage: $0 <reject-untrusted-request|validate-request|verify-target|update-policy|open-pr>" >&2
    exit 2
    ;;
esac
